'use client';

import React, { useState } from 'react';
import {
  HelpCircle,
  BookOpen,
  DollarSign,
  ChevronDown,
  ChevronRight,
  Search,
  FileSpreadsheet,
  Link2,
  Zap,
  Download,
  ArrowLeft,
  ArrowRight,
  Sparkles,
  ShieldCheck,
  LayoutList,
  Code2,
  Copy,
  Check,
  Terminal,
  ExternalLink,
} from 'lucide-react';
import { useTenantDomains } from '../../hooks/useTenantDomains';

type HelpSection = 'list' | 'quickstart' | 'createlink' | 'bulkcsv' | 'webhooks' | 'faq' | 'api';

export const HelpGuideView: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [search, setSearch] = useState('');
  const [activeSection, setActiveSection] = useState<HelpSection>('list');
  const [codeLang, setCodeLang] = useState<'curl' | 'php' | 'node' | 'python'>('curl');
  const [copiedCode, setCopiedCode] = useState(false);
  const { defaultDomain } = useTenantDomains();

  const guides = [
    {
      id: 'quickstart' as const,
      title: '1. Quick Start Guide',
      category: 'Basics',
      icon: Zap,
      description: 'Create your first branded short link, test sub-2ms edge redirection, and embed into DLT SMS templates.',
      tags: ['quickstart', 'short links', 'redirection', 'sms'],
    },
    {
      id: 'createlink' as const,
      title: '2. Creating & Customizing Links',
      category: 'Configuration',
      icon: Link2,
      description: 'Configure custom slug aliases, ERP external reference tracking, click caps, and TRAI 160-char SMS limits.',
      tags: ['alias', 'external_ref', 'invoice', 'expiration', 'trai'],
    },
    {
      id: 'bulkcsv' as const,
      title: '3. Bulk CSV Format Guide',
      category: 'Spreadsheets',
      icon: FileSpreadsheet,
      description: 'Required columns, batch formatting specs, and downloadable CSV templates for generating hundreds of links.',
      tags: ['bulk', 'csv', 'batch', 'template', 'spreadsheet'],
    },
    {
      id: 'webhooks' as const,
      title: '4. Webhooks & Closed-Loop Attribution',
      category: 'Integrations',
      icon: DollarSign,
      description: 'Set up payment gateway callbacks, API authorization headers, and automatic conversion reconciliation.',
      tags: ['webhook', 'outcomes', 'api key', 'payments', 'conversions'],
    },
    {
      id: 'api' as const,
      title: '5. Enterprise API & ERP Integration',
      category: 'Developers',
      icon: Code2,
      description: 'Production REST API reference for single/bulk links, dynamic QR codes, webhook revenue attribution, and multi-language code snippets.',
      tags: ['api', 'rest', 'developer', 'curl', 'php', 'laravel', 'python', 'nodejs', 'erp', 'endpoints', 'json'],
    },
    {
      id: 'faq' as const,
      title: '6. FAQs & Regulatory Compliance',
      category: 'Compliance',
      icon: HelpCircle,
      description: 'TRAI DLT portal whitelisting, DPDP Act 2023 privacy safeguards, dynamic vector QR codes, and telecom rules.',
      tags: ['faq', 'dlt', 'trai', 'dpdp', 'qr codes', 'privacy'],
    },
  ];

  const faqs = [
    {
      q: 'Why are short links essential for SMS campaigns?',
      a: `A single SMS is capped at 160 GSM-7 characters. A full tracking URL takes over 110 characters, doubling or tripling telecom bills. Shortly compresses URLs to ~18 characters (${defaultDomain}/fHXV8q), keeping SMS alerts within a single unit and cutting telecom bills by 50–70%.`,
    },
    {
      q: 'What is TRAI DLT compliance and why must domains be whitelisted?',
      a: `Under TRAI regulations, any URL inside an SMS template delivered across Indian networks (Jio, Airtel, Vi) must belong to a pre-whitelisted domain on telecom DLT portals. Shortly provides ${defaultDomain} as a pre-approved shared domain and supports custom domains.`,
    },
    {
      q: 'How does Closed-Loop Outcome Attribution work?',
      a: 'When a link is generated, Shortly binds an externalRef (such as an order ID or invoice number). When a payment or conversion occurs, your backend sends an automated webhook to Shortly. The system matches the conversion to the exact link clicked, providing true conversion ROI.',
    },
    {
      q: 'Are QR codes generated by Shortly dynamic or static?',
      a: 'All QR codes in Shortly are 100% dynamic vector codes. They point to your branded short URL which redirects to the destination. You can print packaging or flyers today and update the destination target later without reprinting physical media.',
    },
    {
      q: 'How does Shortly adhere to India DPDP Act 2023?',
      a: 'Visitor IP addresses are immediately salted and hashed with a rotating secret key before database persistence. Raw IP addresses are never stored. Click streams are aggregated into 24-hour analytical rollups, safeguarding visitor privacy.',
    },
  ];

  const filteredGuides = guides.filter(
    (g) =>
      g.title.toLowerCase().includes(search.toLowerCase()) ||
      g.description.toLowerCase().includes(search.toLowerCase()) ||
      g.tags.some((t) => t.toLowerCase().includes(search.toLowerCase()))
  );

  const filteredFaqs = faqs.filter(
    (f) =>
      f.q.toLowerCase().includes(search.toLowerCase()) ||
      f.a.toLowerCase().includes(search.toLowerCase())
  );

  const downloadSampleTemplate = () => {
    const sample = `destination_url,alias,tag,external_ref\nhttps://example.com/pay?inv=INV-2026-001,pay-001,Payment,INV-2026-001\nhttps://example.com/pay?inv=INV-2026-002,pay-002,Payment,INV-2026-002\nhttps://example.com/offer/summer,summer-offer,Marketing,CMP-2026-01`;
    const blob = new Blob([sample], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'jlmp_bulk_links_template.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  const renderBackToListButton = () => (
    <div className="pb-3 border-b border-slate-100 flex items-center justify-between">
      <button
        onClick={() => setActiveSection('list')}
        aria-label="Back to all guides list"
        className="inline-flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-800 transition min-h-[40px] px-2.5 py-1 rounded-md hover:bg-blue-50 cursor-pointer"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Back to all guides</span>
      </button>
      {search && (
        <span className="text-[11px] text-slate-500 font-mono">
          Search preserved: &ldquo;{search}&rdquo;
        </span>
      )}
    </div>
  );

  return (
    <div className="space-y-4 w-full">
      {/* Header Banner */}
      <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-2xs flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-md bg-slate-100 flex items-center justify-center text-slate-600">
            <BookOpen className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-base font-semibold text-slate-900 tracking-tight">
              Help & Knowledge Base
            </h1>
            <p className="text-xs text-slate-500 mt-0.5">
              Operational guides, CSV specifications, and compliance references.
            </p>
          </div>
        </div>

        {/* Persistent Docs Search Input */}
        <div className="relative">
          <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-2.5" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search documentation..."
            aria-label="Search documentation"
            className="w-64 text-xs pl-8 pr-3 py-2 rounded-lg border border-slate-300 focus:outline-none focus:ring-1 focus:ring-blue-500 bg-white min-h-[40px]"
          />
        </div>
      </div>

      {/* Navigation Ribbon */}
      <div className="flex flex-wrap items-center gap-1.5 bg-white p-1.5 rounded-lg border border-slate-200/80 shadow-2xs text-xs font-semibold text-slate-600">
        <button
          onClick={() => setActiveSection('list')}
          className={`flex items-center gap-1.5 px-3 py-2 rounded-md transition min-h-[40px] cursor-pointer ${
            activeSection === 'list'
              ? 'bg-blue-600 text-white font-bold shadow-xs'
              : 'hover:bg-slate-100 text-slate-700'
          }`}
        >
          <LayoutList className="w-3.5 h-3.5" />
          <span>All Guides</span>
        </button>

        {[
          { id: 'quickstart' as const, label: '1. Quick Start', icon: Zap },
          { id: 'createlink' as const, label: '2. Creating Links', icon: Link2 },
          { id: 'bulkcsv' as const, label: '3. Bulk CSV Format', icon: FileSpreadsheet },
          { id: 'webhooks' as const, label: '4. Webhooks', icon: DollarSign },
          { id: 'api' as const, label: '5. Enterprise API', icon: Code2 },
          { id: 'faq' as const, label: '6. FAQs', icon: HelpCircle },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeSection === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveSection(tab.id)}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-md transition min-h-[40px] cursor-pointer ${
                isActive
                  ? 'bg-blue-600 text-white font-bold shadow-xs'
                  : 'hover:bg-slate-100 text-slate-700'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* SECTION: DIRECTORY LIST OF ALL GUIDES */}
      {activeSection === 'list' && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredGuides.map((guide) => {
              const Icon = guide.icon;
              return (
                <div
                  key={guide.id}
                  onClick={() => setActiveSection(guide.id)}
                  className="bg-white p-5 rounded-lg border border-slate-200 shadow-2xs hover:border-blue-400 hover:shadow-xs transition cursor-pointer flex flex-col justify-between space-y-3 group"
                >
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center group-hover:bg-blue-600 group-hover:text-white transition">
                        <Icon className="w-4 h-4" />
                      </div>
                      <span className="text-[10px] font-mono text-slate-500 uppercase font-semibold bg-slate-100 px-2 py-0.5 rounded">
                        {guide.category}
                      </span>
                    </div>
                    <h3 className="font-bold text-slate-900 text-sm group-hover:text-blue-600 transition">
                      {guide.title}
                    </h3>
                    <p className="text-xs text-slate-600 leading-relaxed">
                      {guide.description}
                    </p>
                  </div>

                  <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs font-semibold text-blue-600">
                    <span>Open Guide</span>
                    <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-1 transition-transform" />
                  </div>
                </div>
              );
            })}
          </div>

          {filteredGuides.length === 0 && (
            <div className="bg-white p-12 text-center rounded-lg border border-slate-200">
              <Search className="w-8 h-8 text-slate-300 mx-auto mb-2" />
              <h3 className="text-sm font-bold text-slate-800">No documentation matched</h3>
              <p className="text-xs text-slate-500 mt-1">
                No guides match &ldquo;{search}&rdquo;. Try clearing your query to browse all topics.
              </p>
            </div>
          )}
        </div>
      )}

      {/* SECTION 1: QUICK START */}
      {activeSection === 'quickstart' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          {renderBackToListButton()}

          <div>
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-500" />
              Getting Started
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Follow these steps to create your first link.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 pt-1">
            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-xs">
                1
              </div>
              <h3 className="font-bold text-xs text-slate-900">Create a Branded Short Link</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Click the <strong>+ Create Link</strong> button in the top navigation bar. Paste your destination URL and specify an optional alias like <code className="bg-slate-200 px-1 py-0.5 rounded font-mono text-slate-800">offer-2026</code>.
              </p>
            </div>

            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-xs">
                2
              </div>
              <h3 className="font-bold text-xs text-slate-900">Verify Sub-2ms Redirection</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Shortly generates a short URL like <code className="bg-slate-200 px-1 py-0.5 rounded font-mono text-blue-700">{defaultDomain}/xyz123</code>. The edge redirect engine routes visitors and responds in &lt; 2ms.
              </p>
            </div>

            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-xs">
                3
              </div>
              <h3 className="font-bold text-xs text-slate-900">Embed into SMS & Track Outcomes</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Copy your short link into your campaigns or DLT templates. When visitors click and convert, revenue automatically attributes to your link.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 2: CREATING & CUSTOMIZING LINKS */}
      {activeSection === 'createlink' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          {renderBackToListButton()}

          <div>
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Link2 className="w-4 h-4 text-blue-600" />
              Link Configuration
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Learn how to configure your links.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            <div className="space-y-3">
              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <h3 className="font-bold text-slate-900">Branded Custom Aliases</h3>
                <p className="text-slate-600 leading-relaxed">
                  Instead of random alphanumeric codes, you can assign memorable slugs such as <span className="font-mono text-blue-600 font-bold">{defaultDomain}/summer-sale</span> or <span className="font-mono text-blue-600 font-bold">{defaultDomain}/product-launch</span>.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <h3 className="font-bold text-slate-900">External Reference Matching</h3>
                <p className="text-slate-600 leading-relaxed">
                  Provide an Order ID or Invoice # in the <strong>External Ref</strong> field (e.g. <span className="font-mono text-slate-800">INV-2026-9021</span>) to match conversions and payments back to this exact link.
                </p>
              </div>
            </div>

            <div className="space-y-3">
              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <h3 className="font-bold text-slate-900">Expiration & Click Quotas</h3>
                <p className="text-slate-600 leading-relaxed">
                  Set expiration dates for time-sensitive campaigns or cap maximum clicks (e.g. first 50 registrations). Expired links automatically route to a clean expiration notice page.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-emerald-50/80 border border-emerald-200 space-y-1.5">
                <h3 className="font-bold text-emerald-900">TRAI 160-Character SMS Rule</h3>
                <p className="text-emerald-800 leading-relaxed">
                  Standard Indian telecom SMS is limited to 160 characters. A long tracking URL consumes 110+ chars, forcing 2 SMS credits. Shortly URLs are ~18 characters, leaving 142 characters for message content.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 3: BULK CSV FORMAT */}
      {activeSection === 'bulkcsv' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          {renderBackToListButton()}

          <div className="flex flex-wrap items-center justify-between pb-2 border-b border-slate-100 gap-3">
            <div>
              <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <FileSpreadsheet className="w-4 h-4 text-emerald-600" />
                Bulk CSV Format
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Rules for generating links in bulk.
              </p>
            </div>

            <button
              onClick={downloadSampleTemplate}
              aria-label="Download Sample CSV Template"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-xs transition min-h-[40px] cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              Download Sample CSV
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-700 border border-slate-200 rounded-lg">
              <thead className="bg-slate-100 text-slate-600 font-bold uppercase text-[10px]">
                <tr>
                  <th className="p-3">Column Name</th>
                  <th className="p-3">Requirement</th>
                  <th className="p-3">Description</th>
                  <th className="p-3">Example Value</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                <tr>
                  <td className="p-3 font-mono font-bold text-blue-600">destination_url</td>
                  <td className="p-3 font-semibold text-red-600">Required</td>
                  <td className="p-3">Full URL starting with http:// or https://</td>
                  <td className="p-3 font-mono text-slate-600">https://example.com/pay?inv=INV-101</td>
                </tr>
                <tr>
                  <td className="p-3 font-mono font-bold text-slate-800">alias</td>
                  <td className="p-3 text-slate-500">Optional</td>
                  <td className="p-3">Custom slug for {defaultDomain}/&lt;alias&gt;</td>
                  <td className="p-3 font-mono text-slate-600">pay-101</td>
                </tr>
                <tr>
                  <td className="p-3 font-mono font-bold text-slate-800">tag</td>
                  <td className="p-3 text-slate-500">Optional</td>
                  <td className="p-3">Campaign grouping category</td>
                  <td className="p-3 font-mono text-slate-600">Payment</td>
                </tr>
                <tr>
                  <td className="p-3 font-mono font-bold text-slate-800">external_ref</td>
                  <td className="p-3 text-slate-500">Optional</td>
                  <td className="p-3">Order ID or Invoice ID for outcome attribution</td>
                  <td className="p-3 font-mono text-slate-600">INV-2026-101</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* SECTION 4: WEBHOOKS & ERP SETUP */}
      {activeSection === 'webhooks' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          {renderBackToListButton()}

          <div>
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <DollarSign className="w-4 h-4 text-emerald-600" />
              Webhook Setup
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Set up webhooks to track conversions.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <h3 className="font-bold text-slate-900">Webhook Endpoint URL</h3>
              <div className="p-2 rounded bg-white border border-slate-300 font-mono text-blue-600 font-bold select-all">
                POST https://{defaultDomain}/api/v1/outcomes
              </div>
              <p className="text-slate-500 mt-1">
                Configure your payment gateway (HDFC, Razorpay, ICICI, PayU) or ERP to trigger this callback upon successful transaction.
              </p>
            </div>

            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <h3 className="font-bold text-slate-900">Required Headers</h3>
              <div className="p-2 rounded bg-white border border-slate-300 font-mono text-slate-700 text-[11px] space-y-1">
                <div>Content-Type: application/json</div>
                <div>Authorization: Bearer &lt;YOUR_API_KEY&gt;</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 5: ENTERPRISE API & ERP INTEGRATION */}
      {activeSection === 'api' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-5">
          {renderBackToListButton()}

          <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-slate-100">
            <div>
              <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <Code2 className="w-4 h-4 text-blue-600" />
                Enterprise REST API & ERP Integration Guide
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Integrate Shortly with your School ERP, WhatsApp bot, SMS gateway, or custom backend.
              </p>
            </div>
            <a
              href="/apikeys"
              onClick={(e) => {
                e.preventDefault();
                window.location.hash = 'apikeys';
              }}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-blue-50 border border-blue-200 text-blue-700 text-xs font-semibold hover:bg-blue-100 transition"
            >
              <span>Manage API Keys</span>
              <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>

          {/* Security & Key Generation Notice */}
          <div className="p-3.5 rounded-lg bg-amber-50/80 border border-amber-200/80 text-xs text-amber-900 space-y-1">
            <div className="font-bold flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-amber-600" />
              <span>Security & Key Provisioning Notice</span>
            </div>
            <p className="text-[11px] text-amber-800 leading-relaxed">
              API Keys are securely provisioned under <strong>Settings ➔ API Keys</strong>. Never expose or hardcode real secret keys into client-side code or public repositories. Pass your secret key via the <code>Authorization: Bearer &lt;YOUR_API_KEY&gt;</code> header.
            </p>
          </div>

          {/* Quick Specifications Strip */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">
              <div className="text-[10px] uppercase font-bold text-slate-400">Base Production URL</div>
              <div className="font-mono font-bold text-blue-600 mt-0.5 truncate">https://{defaultDomain}/api/v1</div>
            </div>
            <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">
              <div className="text-[10px] uppercase font-bold text-slate-400">Authentication Header</div>
              <div className="font-mono font-bold text-slate-800 mt-0.5 truncate">Authorization: Bearer &lt;KEY&gt;</div>
            </div>
            <div className="p-3 rounded-lg bg-slate-50 border border-slate-200">
              <div className="text-[10px] uppercase font-bold text-slate-400">Response Format</div>
              <div className="font-mono font-bold text-slate-800 mt-0.5 truncate">JSON (RFC 8259 Envelope)</div>
            </div>
          </div>

          {/* Interactive Code Snippets Box */}
          <div className="rounded-lg border border-slate-800 bg-slate-950 overflow-hidden text-xs">
            <div className="flex items-center justify-between px-3 py-2 bg-slate-900 border-b border-slate-800">
              <div className="flex items-center gap-1">
                {(['curl', 'php', 'node', 'python'] as const).map((lang) => (
                  <button
                    key={lang}
                    onClick={() => setCodeLang(lang)}
                    className={`px-2.5 py-1 rounded text-[11px] font-mono font-semibold transition cursor-pointer ${
                      codeLang === lang
                        ? 'bg-blue-600 text-white shadow-2xs'
                        : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
                    }`}
                  >
                    {lang === 'curl' ? 'cURL' : lang === 'php' ? 'PHP (Laravel)' : lang === 'node' ? 'Node.js' : 'Python'}
                  </button>
                ))}
              </div>

              <button
                onClick={() => {
                  let textToCopy = '';
                  if (codeLang === 'curl') {
                    textToCopy = `curl -X POST "https://${defaultDomain}/api/v1/links" \\\n  -H "Authorization: Bearer YOUR_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"destinationUrl": "https://erp.jupsoft.com/fees/pay?inv=INV-2026-001", "alias": "fee-inv-001", "externalRef": "INV-2026-001", "tag": "Fees"}'`;
                  } else if (codeLang === 'php') {
                    textToCopy = `// Laravel HTTP Client\n$res = Http::withToken($apiKey)->post('https://${defaultDomain}/api/v1/links', [\n    'destinationUrl' => 'https://erp.jupsoft.com/fees/pay?inv=INV-2026-001',\n    'externalRef'    => 'INV-2026-001',\n    'tag'            => 'School-Fees',\n]);\n$shortUrl = $res->json('data.shortUrl');`;
                  } else if (codeLang === 'node') {
                    textToCopy = `// Node.js Axios\nconst res = await axios.post('https://${defaultDomain}/api/v1/links', {\n  destinationUrl: 'https://erp.jupsoft.com/fees/pay?inv=INV-2026-001',\n  externalRef: 'INV-2026-001',\n  tag: 'School-Fees',\n}, {\n  headers: { Authorization: \`Bearer \${API_KEY}\` }\n});\nconsole.log(res.data.data.shortUrl);`;
                  } else {
                    textToCopy = `# Python requests\nimport requests\nres = requests.post('https://${defaultDomain}/api/v1/links', json={\n    'destinationUrl': 'https://erp.jupsoft.com/fees/pay?inv=INV-2026-001',\n    'externalRef': 'INV-2026-001',\n    'tag': 'School-Fees'\n}, headers={'Authorization': f'Bearer {API_KEY}'})\nprint(res.json()['data']['shortUrl'])`;
                  }
                  navigator.clipboard.writeText(textToCopy).catch(() => {});
                  setCopiedCode(true);
                  setTimeout(() => setCopiedCode(false), 2000);
                }}
                className="flex items-center gap-1 text-[11px] text-slate-300 hover:text-white px-2 py-1 rounded hover:bg-slate-800 transition cursor-pointer"
              >
                {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedCode ? 'Copied' : 'Copy Code'}</span>
              </button>
            </div>

            <pre className="p-4 text-slate-300 font-mono text-[11px] leading-relaxed overflow-x-auto select-all">
              {codeLang === 'curl' && `curl -X POST "https://${defaultDomain}/api/v1/links" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "destinationUrl": "https://erp.jupsoft.com/fees/pay?inv=INV-2026-001",
    "alias": "fee-inv-001",
    "externalRef": "INV-2026-001",
    "tag": "School-Fees",
    "expiresAt": "2026-10-31T23:59:59.000Z"
  }'`}

              {codeLang === 'php' && `// Laravel / PHP Integration
use Illuminate\\Support\\Facades\\Http;

$response = Http::withToken($apiKey)->post('https://${defaultDomain}/api/v1/links', [
    'destinationUrl' => 'https://erp.jupsoft.com/fees/pay?inv=' . $invoiceNo,
    'alias'          => 'fee-' . strtolower($invoiceNo),
    'externalRef'    => $invoiceNo,
    'tag'            => 'School-Fees',
    'expiresAt'      => now()->addDays(30)->toIso8601String(),
]);

$shortUrl = $response->json('data.shortUrl');`}

              {codeLang === 'node' && `// Node.js (Axios / Fetch)
import axios from 'axios';

const { data } = await axios.post('https://${defaultDomain}/api/v1/links', {
  destinationUrl: \`https://erp.jupsoft.com/fees/pay?inv=\${invoiceNo}\`,
  alias: \`fee-\${invoiceNo.toLowerCase()}\`,
  externalRef: invoiceNo,
  tag: 'School-Fees',
  expiresAt: new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString(),
}, {
  headers: {
    'Authorization': \`Bearer \${process.env.SHORTLY_API_KEY}\`,
    'Content-Type': 'application/json'
  }
});

console.log('Short URL:', data.data.shortUrl);`}

              {codeLang === 'python' && `# Python 3.8+ (requests)
import requests

payload = {
    "destinationUrl": f"https://erp.jupsoft.com/fees/pay?inv={invoice_no}",
    "alias": f"fee-{invoice_no.lower()}",
    "externalRef": invoice_no,
    "tag": "School-Fees"
}

res = requests.post(
    "https://${defaultDomain}/api/v1/links",
    json=payload,
    headers={"Authorization": f"Bearer {API_KEY}"}
)
short_url = res.json()["data"]["shortUrl"]`}
            </pre>
          </div>

          {/* Core Endpoints Grid */}
          <div className="space-y-3 pt-2">
            <h3 className="font-bold text-slate-900 text-xs uppercase tracking-wide">
              Production Endpoints Reference
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <div className="flex items-center gap-2 font-mono">
                  <span className="px-1.5 py-0.5 rounded bg-emerald-100 text-emerald-800 font-bold text-[10px]">POST</span>
                  <span className="font-bold text-slate-800">/api/v1/links</span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">
                  Generate branded single links with custom alias, DLT-safe short length, expiration timer, and external reference.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <div className="flex items-center gap-2 font-mono">
                  <span className="px-1.5 py-0.5 rounded bg-emerald-100 text-emerald-800 font-bold text-[10px]">POST</span>
                  <span className="font-bold text-slate-800">/api/v1/links/bulk</span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">
                  Generate thousands of links in one atomic batch for mass SMS or WhatsApp fee dispatch campaigns.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <div className="flex items-center gap-2 font-mono">
                  <span className="px-1.5 py-0.5 rounded bg-amber-100 text-amber-800 font-bold text-[10px]">PATCH</span>
                  <span className="font-bold text-slate-800">/api/v1/links/:id</span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">
                  Update target destination URL, pause link, or change timer expiration with sub-millisecond cache refresh.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <div className="flex items-center gap-2 font-mono">
                  <span className="px-1.5 py-0.5 rounded bg-blue-100 text-blue-800 font-bold text-[10px]">POST</span>
                  <span className="font-bold text-slate-800">/api/v1/outcomes</span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">
                  Reconcile payment success callbacks from Razorpay/PayU/ERP back to the link via <code>externalRef</code>.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <div className="flex items-center gap-2 font-mono">
                  <span className="px-1.5 py-0.5 rounded bg-purple-100 text-purple-800 font-bold text-[10px]">GET</span>
                  <span className="font-bold text-slate-800">/api/v1/links/:id/qr</span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">
                  Dynamic Vector QR code in SVG or 1024px PNG with <code>?size=1024&format=png</code> for ID cards and print media.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <div className="flex items-center gap-2 font-mono">
                  <span className="px-1.5 py-0.5 rounded bg-slate-200 text-slate-800 font-bold text-[10px]">GET</span>
                  <span className="font-bold text-slate-800">/api/v1/analytics/summary</span>
                </div>
                <p className="text-slate-600 text-[11px] leading-relaxed">
                  Pull click counts, unique visitors, devices (Mobile/Desktop), browsers, and referrers directly into ERP.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 6: FAQs & COMPLIANCE */}
      {activeSection === 'faq' && (
        <div className="bg-white rounded-lg border border-slate-200/80 shadow-2xs overflow-hidden">
          <div className="p-4 border-b border-slate-200">
            {renderBackToListButton()}
          </div>

          <div className="px-5 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
            <span className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-1.5">
              <HelpCircle className="w-3.5 h-3.5 text-blue-600" />
              Frequently Asked Questions ({filteredFaqs.length})
            </span>
            <span className="text-[11px] text-slate-500 font-mono">Compliance</span>
          </div>

          <div className="divide-y divide-slate-100">
            {filteredFaqs.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="transition">
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    aria-label={`Toggle question: ${faq.q}`}
                    className="w-full text-left px-5 py-3 text-xs font-semibold text-slate-800 hover:bg-slate-50 flex items-center justify-between gap-3 min-h-[40px] cursor-pointer"
                  >
                    <span className="flex items-center gap-2">
                      <span className="text-blue-600 font-mono font-bold">0{idx + 1}.</span>
                      {faq.q}
                    </span>
                    {isOpen ? (
                      <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                    ) : (
                      <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
                    )}
                  </button>

                  {isOpen && (
                    <div className="px-5 pb-4 pt-1 text-xs text-slate-600 bg-slate-50/50 leading-relaxed border-t border-slate-100">
                      <div className="pl-4 border-l-2 border-blue-500 py-0.5">
                        {faq.a}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};
