'use client';

import React, { useState } from 'react';
import {
  HelpCircle,
  BookOpen,
  ShieldCheck,
  Smartphone,
  DollarSign,
  QrCode,
  Building2,
  ChevronDown,
  ChevronRight,
  Search,
  ExternalLink,
  LifeBuoy,
  FileSpreadsheet,
  Link2,
  Zap,
  Download,
  Copy,
  Check,
  CheckCircle2,
} from 'lucide-react';

import { useTenantDomains } from '../../hooks/useTenantDomains';

export const HelpGuideView: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [search, setSearch] = useState('');
  const [activeSection, setActiveSection] = useState<'quickstart' | 'createlink' | 'bulkcsv' | 'webhooks' | 'faq'>('quickstart');
  const [copiedKey, setCopiedKey] = useState(false);
  const { defaultDomain } = useTenantDomains();

  const faqs = [
    {
      q: 'Why are short links mandatory for Indian School SMS campaigns?',
      a: `A single SMS is capped at 160 GSM-7 characters. A full ERP fee link takes over 110 characters, doubling or tripling telecom bills. Shortly compresses URLs to ~18 characters (${defaultDomain}/fHXV8q), keeping SMS alerts within a single unit and cutting telecom bills by 50–70%.`,
    },
    {
      q: 'What is TRAI DLT compliance and why must domains be whitelisted?',
      a: `Under TRAI regulations, any URL inside an SMS template delivered across Indian networks (Jio, Airtel, Vi) must belong to a pre-whitelisted domain on telecom DLT portals. Shortly provides ${defaultDomain} as a pre-approved shared domain and supports custom school subdomains.`,
    },
    {
      q: 'How does Closed-Loop Outcome Attribution work?',
      a: 'When an SMS link is generated, Shortly binds an externalRef (student admission or invoice number). When parents pay online, eConnect ERP sends an automated webhook to Shortly. The system matches the payment to the exact SMS link clicked, providing true conversion ROI.',
    },
    {
      q: 'Are QR codes generated by Shortly dynamic or static?',
      a: 'All QR codes in Shortly are 100% dynamic vector codes. They point to your branded short URL which redirects to the destination. You can print student ID cards or flyers today and update the destination target next year without reprinting physical media.',
    },
    {
      q: 'How does Shortly adhere to India DPDP Act 2023?',
      a: 'Visitor IP addresses are immediately salted and hashed with a rotating secret key before database persistence. Raw IP addresses are never stored. Click streams are aggregated into 24-hour analytical rollups, safeguarding parent and student privacy.',
    },
  ];

  const filteredFaqs = faqs.filter(
    (f) =>
      f.q.toLowerCase().includes(search.toLowerCase()) ||
      f.a.toLowerCase().includes(search.toLowerCase())
  );

  const downloadSampleTemplate = () => {
    const sample = `destination_url,alias,tag,external_ref\nhttps://jupsoft.com/fees/pay?inv=INV-2026-001,fee-std1-001,Class 10 Fees,INV-2026-001\nhttps://jupsoft.com/fees/pay?inv=INV-2026-002,fee-std1-002,Class 10 Fees,INV-2026-002\nhttps://jupsoft.com/notice/parent-teacher-meet,ptm-april,Academic Notices,PTM-APR-26`;
    const blob = new Blob([sample], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'jlmp_bulk_links_template.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4 max-w-7xl mx-auto">
      {/* Header Banner */}
      <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3.5">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/jupsoft-logo.png"
            alt="Jupsoft Shortly"
            className="w-12 h-12 object-contain bg-slate-50 border border-slate-200 rounded-lg p-1 shrink-0"
          />
          <div>
            <h1 className="text-base font-bold text-slate-900 tracking-tight flex items-center gap-2">
              Help Guide
              <span className="text-[10px] bg-blue-50 text-blue-700 border border-blue-200/60 font-semibold px-2 py-0.5 rounded-full">
                Guide
              </span>
            </h1>
            <p className="text-xs text-slate-500 mt-0.5">
              Learn how to use the platform.
            </p>
          </div>
        </div>

        {/* Search Input with accessible label */}
        <div className="relative">
          <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-2" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search documentation..."
            aria-label="Search documentation"
            className="w-56 text-xs pl-7 pr-3 py-1.5 rounded-lg border border-slate-300 focus:outline-none focus:ring-1 focus:ring-blue-500 bg-white"
          />
        </div>
      </div>

      {/* Navigation Tabs (4 Core Sections + FAQ) */}
      <div className="flex flex-wrap items-center gap-1.5 bg-white p-1.5 rounded-lg border border-slate-200/80 shadow-2xs text-xs font-semibold text-slate-600">
        {[
          { id: 'quickstart', label: '1. Quick Start', icon: Zap },
          { id: 'createlink', label: '2. Creating Links', icon: Link2 },
          { id: 'bulkcsv', label: '3. Bulk CSV Format', icon: FileSpreadsheet },
          { id: 'webhooks', label: '4. Webhooks', icon: DollarSign },
          { id: 'faq', label: '5. FAQs', icon: HelpCircle },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeSection === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveSection(tab.id as any)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md transition ${
                isActive
                  ? 'bg-blue-600 text-white font-bold shadow-xs'
                  : 'hover:bg-slate-100 text-slate-700'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* SECTION 1: QUICK START */}
      {activeSection === 'quickstart' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          <div className="border-b border-slate-100 pb-2">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-500" />
              Getting Started
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Follow these steps to create your first link.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 pt-1">
            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-xs">
                1
              </div>
              <h3 className="font-bold text-xs text-slate-900">Create a Branded Short Link</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Click the red <strong>+ Create Link</strong> button on the top right. Paste your destination URL (e.g. your eConnect fee portal) and specify an optional alias like <code className="bg-slate-200 px-1 py-0.5 rounded font-mono text-slate-800">fee-apr26</code>.
              </p>
            </div>

            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-xs">
                2
              </div>
              <h3 className="font-bold text-xs text-slate-900">Verify Sub-2ms Redirection</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Shortly generates a short URL like <code className="bg-slate-200 px-1 py-0.5 rounded font-mono text-blue-700">{defaultDomain}/xyz123</code>. The edge redirect engine routes visitors and responds in &lt; 2ms.
              </p>
            </div>

            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <div className="w-7 h-7 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center text-xs">
                3
              </div>
              <h3 className="font-bold text-xs text-slate-900">Embed into SMS & Track Fees</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Copy your 18-character short link into your Airtel/Jio approved DLT template. When parents click and pay, revenue automatically attributes to your link.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 2: CREATING & CUSTOMIZING LINKS */}
      {activeSection === 'createlink' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          <div className="border-b border-slate-100 pb-2">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Link2 className="w-4 h-4 text-blue-600" />
              Link Configuration
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Learn how to configure your links.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            <div className="space-y-3">
              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <h3 className="font-bold text-slate-900">Branded Custom Aliases</h3>
                <p className="text-slate-600 leading-relaxed">
                  Instead of random alphanumeric codes, you can assign memorable slugs such as <span className="font-mono text-blue-600 font-bold">{defaultDomain}/annual-sports-day</span> or <span className="font-mono text-blue-600 font-bold">{defaultDomain}/ptm-notice</span>.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <h3 className="font-bold text-slate-900">External ERP Reference Matching</h3>
                <p className="text-slate-600 leading-relaxed">
                  Always provide the student Admission Number or Fee Invoice # in the <strong>External Ref</strong> field (e.g. <span className="font-mono text-slate-800">INV-2026-9021</span>). This allows eConnect ERP to match bank payments to this exact link.
                </p>
              </div>
            </div>

            <div className="space-y-3">
              <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 space-y-1.5">
                <h3 className="font-bold text-slate-900">Expiration & Click Quotas</h3>
                <p className="text-slate-600 leading-relaxed">
                  Set expiration dates for time-sensitive circulars (e.g. PTM booking forms) or cap maximum clicks (e.g. first 50 seats for a school trip). Expired links automatically route to a friendly school notice page.
                </p>
              </div>

              <div className="p-3.5 rounded-lg bg-emerald-50/80 border border-emerald-200 space-y-1.5">
                <h3 className="font-bold text-emerald-900">TRAI 160-Character SMS Rule</h3>
                <p className="text-emerald-800 leading-relaxed">
                  Standard Indian telecom SMS is limited to 160 characters. A standard ERP link consumes 110+ chars, forcing 2 SMS credits. Shortly URLs are strictly 18 characters, leaving 142 characters for message content.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 3: BULK CSV FORMAT */}
      {activeSection === 'bulkcsv' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          <div className="flex flex-wrap items-center justify-between pb-2 border-b border-slate-100 gap-3">
            <div>
              <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <FileSpreadsheet className="w-4 h-4 text-emerald-600" />
                Bulk CSV Format
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Rules for generating links in bulk.
              </p>
            </div>

            <button
              onClick={downloadSampleTemplate}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow-xs transition"
            >
              <Download className="w-3.5 h-3.5" />
              Download Sample CSV
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-700 border border-slate-200 rounded-lg">
              <thead className="bg-slate-100 text-slate-600 font-bold uppercase text-[10px]">
                <tr>
                  <th className="p-3">Column Name</th>
                  <th className="p-3">Requirement</th>
                  <th className="p-3">Description</th>
                  <th className="p-3">Example Value</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                <tr>
                  <td className="p-3 font-mono font-bold text-blue-600">destination_url</td>
                  <td className="p-3 font-semibold text-red-600">Required</td>
                  <td className="p-3">Full URL starting with http:// or https://</td>
                  <td className="p-3 font-mono text-slate-600">https://jupsoft.com/fees/pay?inv=INV-101</td>
                </tr>
                <tr>
                  <td className="p-3 font-mono font-bold text-slate-800">alias</td>
                  <td className="p-3 text-slate-500">Optional</td>
                  <td className="p-3">Custom slug for jup.link/&lt;alias&gt;</td>
                  <td className="p-3 font-mono text-slate-600">fee-std1-101</td>
                </tr>
                <tr>
                  <td className="p-3 font-mono font-bold text-slate-800">tag</td>
                  <td className="p-3 text-slate-500">Optional</td>
                  <td className="p-3">Campaign grouping category</td>
                  <td className="p-3 font-mono text-slate-600">Fee Collection</td>
                </tr>
                <tr>
                  <td className="p-3 font-mono font-bold text-slate-800">external_ref</td>
                  <td className="p-3 text-slate-500">Optional</td>
                  <td className="p-3">Admission number or Invoice ID for fee attribution</td>
                  <td className="p-3 font-mono text-slate-600">INV-2026-101</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* SECTION 4: WEBHOOKS & ERP SETUP */}
      {activeSection === 'webhooks' && (
        <div className="bg-white p-5 rounded-lg border border-slate-200/80 shadow-2xs space-y-4">
          <div className="border-b border-slate-100 pb-2">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <DollarSign className="w-4 h-4 text-emerald-600" />
              Webhook Setup
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Set up webhooks to track conversions.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <h3 className="font-bold text-slate-900">Webhook Endpoint URL</h3>
              <div className="p-2 rounded bg-white border border-slate-300 font-mono text-blue-600 font-bold">
                POST https://api.yourdomain.com/api/v1/outcomes
              </div>
              <p className="text-slate-500 mt-1">
                Configure your payment gateway (HDFC, Razorpay, ICICI) or ERP to trigger this callback upon successful transaction.
              </p>
            </div>

            <div className="p-4 rounded-lg bg-slate-50 border border-slate-200 space-y-2">
              <h3 className="font-bold text-slate-900">Required Headers</h3>
              <div className="p-2 rounded bg-white border border-slate-300 font-mono text-slate-700 text-[11px] space-y-1">
                <div>Content-Type: application/json</div>
                <div>x-api-key: your_api_key_here</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SECTION 5: FAQs & COMPLIANCE */}
      {activeSection === 'faq' && (
        <div className="bg-white rounded-lg border border-slate-200/80 shadow-2xs overflow-hidden">
          <div className="px-5 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
            <span className="text-xs font-bold text-slate-900 uppercase tracking-wide flex items-center gap-1.5">
              <HelpCircle className="w-3.5 h-3.5 text-blue-600" />
              Frequently Asked Questions ({filteredFaqs.length})
            </span>
            <span className="text-[11px] text-slate-500 font-mono">Compliance</span>
          </div>

          <div className="divide-y divide-slate-100">
            {filteredFaqs.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="transition">
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    aria-label={`Toggle question: ${faq.q}`}
                    className="w-full text-left px-5 py-3 text-xs font-semibold text-slate-800 hover:bg-slate-50 flex items-center justify-between gap-3"
                  >
                    <span className="flex items-center gap-2">
                      <span className="text-blue-600 font-mono font-bold">0{idx + 1}.</span>
                      {faq.q}
                    </span>
                    {isOpen ? (
                      <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                    ) : (
                      <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
                    )}
                  </button>

                  {isOpen && (
                    <div className="px-5 pb-4 pt-1 text-xs text-slate-600 bg-slate-50/50 leading-relaxed border-t border-slate-100">
                      <div className="pl-4 border-l-2 border-blue-500 py-0.5">
                        {faq.a}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};
